"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import {
  calculateLandCapacity,
  formatSquareMetres,
} from "@/lib/developer/land-capacity";
import { errorResult } from "@/server/errors/result";
import { getDeveloperAccountByOwnerProfileId } from "@/server/repositories/developer.repository";
import { createDeveloperEstate } from "@/server/repositories/developer-estates.repository";
import { createDeveloperPlotsBulk } from "@/server/repositories/developer-plots.repository";
import { requireDeveloper } from "@/server/services/auth.service";
import { createSupabaseAdminClient } from "@/server/supabase/admin";
import type { AuthActionState } from "@/server/types/auth.types";
import {
  createDeveloperEstateSchema,
  type EstatePlotNumberingStyle,
} from "@/server/validators/developer-estate.schema";

function toActionError(error: unknown): AuthActionState {
  const result = errorResult(error);

  return {
    ok: false,
    message: result.message,
    fieldErrors: "fieldErrors" in result ? result.fieldErrors : undefined,
  };
}

function nullableText(value: string) {
  const trimmed = value.trim();

  return trimmed.length > 0 ? trimmed : null;
}

function getAlphabetLabel(index: number) {
  let value = index;
  let label = "";

  while (value >= 0) {
    label = String.fromCharCode(65 + (value % 26)) + label;
    value = Math.floor(value / 26) - 1;
  }

  return label;
}

function createGeneratedPlotNumber(params: {
  index: number;
  numberingStyle: EstatePlotNumberingStyle;
  startingNumber: number;
  labelPrefix: string;
  plotsPerBlock: number;
}) {
  const number = params.startingNumber + params.index;
  const cleanPrefix = params.labelPrefix.trim() || "A";

  if (params.numberingStyle === "prefixed_numeric") {
    return `${cleanPrefix}${number}`;
  }

  if (params.numberingStyle === "block_numeric") {
    const blockIndex = Math.floor(params.index / params.plotsPerBlock);
    const plotNumberInBlock = (params.index % params.plotsPerBlock) + 1;
    const blockLabel = getAlphabetLabel(blockIndex);

    return `Block ${blockLabel} - Plot ${plotNumberInBlock}`;
  }

  return `Plot ${number}`;
}

function createGeneratedPlotNumbers(params: {
  count: number;
  numberingStyle: EstatePlotNumberingStyle;
  startingNumber: number;
  labelPrefix: string;
  plotsPerBlock: number;
}) {
  return Array.from({ length: params.count }, (_, index) =>
    createGeneratedPlotNumber({
      index,
      numberingStyle: params.numberingStyle,
      startingNumber: params.startingNumber,
      labelPrefix: params.labelPrefix,
      plotsPerBlock: params.plotsPerBlock,
    }),
  );
}

function normalisePlotNumber(value: string) {
  return value.trim().toLowerCase();
}

function buildPlotGenerationNote(params: {
  landSizeValue: number;
  landSizeUnit: string;
  grossLandSizeSqm: number;
  reservedLandPercentage: number;
  usableLandSizeSqm: number;
  plotSizeSqm: number;
  maximumPlots: number;
  plotNote: string;
}) {
  const parts = [
    `Generated by Piedras from ${params.landSizeValue} ${params.landSizeUnit}.`,
    `Gross land: ${formatSquareMetres(params.grossLandSizeSqm)} sqm.`,
    `Reserved/common area: ${params.reservedLandPercentage}%.`,
    `Usable land: ${formatSquareMetres(params.usableLandSizeSqm)} sqm.`,
    `Plot size: ${formatSquareMetres(params.plotSizeSqm)} sqm.`,
    `Maximum calculated capacity: ${params.maximumPlots} plots.`,
    params.plotNote,
  ].filter(Boolean);

  return parts.join(" ");
}

async function deleteCreatedEstateAfterPlotFailure(params: {
  estateId: string;
  developerAccountId: string;
}) {
  const supabase = createSupabaseAdminClient();

  await supabase
    .from("developer_estates")
    .delete()
    .eq("id", params.estateId)
    .eq("developer_account_id", params.developerAccountId);
}

export async function createDeveloperEstateAction(
  _previousState: AuthActionState,
  formData: FormData,
): Promise<AuthActionState> {
  let estateId: string | null = null;
  let developerAccountId: string | null = null;

  try {
    const developer = await requireDeveloper();

    const parsed = createDeveloperEstateSchema.parse({
      estateName: formData.get("estateName"),
      location: formData.get("location"),
      city: formData.get("city"),
      state: formData.get("state"),
      lga: formData.get("lga"),
      description: formData.get("description"),
      status: formData.get("status") || "planning",
      initialPaymentPercentage: formData.get("initialPaymentPercentage"),
      balanceSpreadMonths: formData.get("balanceSpreadMonths"),
      landSizeValue: formData.get("landSizeValue"),
      landSizeUnit: formData.get("landSizeUnit"),
      reservedLandPercentage: formData.get("reservedLandPercentage") || "0",
      numberOfPlots: formData.get("numberOfPlots"),
      plotSizeSqm: formData.get("plotSizeSqm"),
      pricePerPlot: formData.get("pricePerPlot"),
      numberingStyle: formData.get("numberingStyle") || "numeric",
      startingNumber: formData.get("startingNumber") || "1",
      labelPrefix: formData.get("labelPrefix"),
      plotsPerBlock: formData.get("plotsPerBlock") || "20",
      plotNote: formData.get("plotNote"),
    });

    const capacity = calculateLandCapacity({
      landSizeValue: parsed.landSizeValue,
      landSizeUnit: parsed.landSizeUnit,
      reservedLandPercentage: parsed.reservedLandPercentage,
      plotSizeSqm: parsed.plotSizeSqm,
    });

    if (parsed.numberOfPlots > capacity.maximumPlots) {
      return {
        ok: false,
        message: `This land can carry only ${capacity.maximumPlots} plot${
          capacity.maximumPlots === 1 ? "" : "s"
        } after reserved/common area is removed.`,
        fieldErrors: {
          numberOfPlots: [
            "Requested plots exceed the calculated land capacity.",
          ],
        },
      };
    }

    const supabase = createSupabaseAdminClient();

    const account = await getDeveloperAccountByOwnerProfileId(
      supabase,
      developer.id,
    );

    if (!account || account.status !== "active") {
      return {
        ok: false,
        message: "Developer account is not active.",
      };
    }

    developerAccountId = account.id;

    const generatedPlotNumbers = createGeneratedPlotNumbers({
      count: parsed.numberOfPlots,
      numberingStyle: parsed.numberingStyle,
      startingNumber: parsed.startingNumber,
      labelPrefix: parsed.labelPrefix,
      plotsPerBlock: parsed.plotsPerBlock,
    });

    const duplicateInGeneratedList = generatedPlotNumbers.find(
      (plotNumber, index) =>
        generatedPlotNumbers.findIndex(
          (item) =>
            normalisePlotNumber(item) === normalisePlotNumber(plotNumber),
        ) !== index,
    );

    if (duplicateInGeneratedList) {
      return {
        ok: false,
        message:
          "Piedras could not generate unique plot labels. Adjust the numbering style and try again.",
      };
    }

    const defaultPaymentPlanMode =
      parsed.initialPaymentPercentage >= 100 ? "outright" : "fixed_installment";

    const estate = await createDeveloperEstate(supabase, {
      developerAccountId: account.id,
      estateName: parsed.estateName,
      location: parsed.location,
      city: nullableText(parsed.city),
      state: parsed.state,
      lga: parsed.lga,
      description: nullableText(parsed.description),
      status: parsed.status,
      initialPaymentPercentage: Number(
        parsed.initialPaymentPercentage.toFixed(2),
      ),
      balanceSpreadMonths:
        parsed.initialPaymentPercentage >= 100 ? 0 : parsed.balanceSpreadMonths,
      installmentInterval: "monthly",
      defaultPaymentPlanMode,
      landSizeValue: Number(parsed.landSizeValue.toFixed(2)),
      landSizeUnit: parsed.landSizeUnit,
      grossLandSizeSqm: capacity.grossLandSizeSqm,
      reservedLandPercentage: Number(parsed.reservedLandPercentage.toFixed(2)),
      usableLandSizeSqm: capacity.usableLandSizeSqm,
      defaultPlotSizeSqm: Number(parsed.plotSizeSqm.toFixed(2)),
      plannedPlotCount: parsed.numberOfPlots,
    });

    estateId = estate.id;

    const plotNote = buildPlotGenerationNote({
      landSizeValue: parsed.landSizeValue,
      landSizeUnit: parsed.landSizeUnit,
      grossLandSizeSqm: capacity.grossLandSizeSqm,
      reservedLandPercentage: parsed.reservedLandPercentage,
      usableLandSizeSqm: capacity.usableLandSizeSqm,
      plotSizeSqm: parsed.plotSizeSqm,
      maximumPlots: capacity.maximumPlots,
      plotNote: parsed.plotNote,
    });

    const insertedCount = await createDeveloperPlotsBulk(supabase, {
      developerAccountId: account.id,
      estateId: estate.id,
      plots: generatedPlotNumbers.map((plotNumber) => ({
        plotNumber,
        sizeLabel: `${formatSquareMetres(parsed.plotSizeSqm)} sqm`,
        price: parsed.pricePerPlot,
        notes: nullableText(plotNote),
      })),
    });

    if (insertedCount !== parsed.numberOfPlots) {
      await deleteCreatedEstateAfterPlotFailure({
        estateId: estate.id,
        developerAccountId: account.id,
      });

      estateId = null;

      return {
        ok: false,
        message:
          "Piedras could not create all plots. Please try again before using this estate.",
      };
    }
  } catch (error) {
    if (estateId && developerAccountId) {
      await deleteCreatedEstateAfterPlotFailure({
        estateId,
        developerAccountId,
      });
    }

    return toActionError(error);
  }

  revalidatePath("/developer/estates");

  if (estateId) {
    redirect(`/developer/estates/${estateId}`);
  }

  return {
    ok: true,
    message: "Estate and plots created successfully.",
  };
}
